### PR TITLE
Unnecessary logs

### PR DESCRIPTION
**Pull request by faust64**
prevent from logging curl output in apache error logs.

### CODE REVIEW

**Comment by metalcated** [comment]
Re-check this commit, branch has a conflict. Thanks

**Comment by faust64** [comment]
uh? Will do...

**Comment by faust64** [comment]
right, precise/trusty, ...
I'll open an other PR.

**Comment by faust64** [comment]
moved here: https://github.com/PatchDashboard/patchdashboard/pull/39

**Pull request closed without merging**
